*** /usr/src/share/man/man4/Makefile.orgi	Tue Feb 25 18:30:16 2014
--- /usr/src/share/man/man4/Makefile	Wed Feb 26 10:44:41 2014
***************
*** 217,222 ****
--- 217,223 ----
  	lge.4 \
  	${_lindev.4} \
  	${_linux.4} \
+ 	lispintro.4 \
  	lmc.4 \
  	lo.4 \
  	lp.4 \
***************
*** 235,240 ****
--- 236,242 ----
  	mac_stub.4 \
  	mac_test.4 \
  	malo.4 \
+ 	map.4 \
  	mcd.4 \
  	md.4 \
  	mem.4 \
