*** /usr/src/include/Makefile.original	Wed Aug  4 17:57:14 2010
--- /usr/src/include/Makefile	Wed Aug  4 17:58:52 2010
***************
*** 49,54 ****
--- 49,55 ----
  	geom/mirror geom/multipath geom/nop \
  	geom/raid3 geom/shsec geom/stripe geom/virstor \
  	netgraph/atm netgraph/netflow \
+ 	net/lisp \
  	security/audit \
  	security/mac_biba security/mac_bsdextended security/mac_lomac \
  	security/mac_mls security/mac_partition \
