*** /usr/src/share/man/man4/Makefile.orig	Thu Apr 21 19:28:11 2016
--- /usr/src/share/man/man4/Makefile	Thu Apr 21 19:28:49 2016
***************
*** 234,239 ****
--- 234,240 ----
  	lge.4 \
  	${_lindev.4} \
  	${_linux.4} \
+ 	lispintro.4 \
  	lmc.4 \
  	lo.4 \
  	lp.4 \
***************
*** 252,257 ****
--- 253,259 ----
  	mac_stub.4 \
  	mac_test.4 \
  	malo.4 \
+ 	map.4 \
  	mcd.4 \
  	md.4 \
  	me.4 \
