*** Makefile.orig	Sat Mar 22 16:34:53 2014
--- Makefile	Sat Mar 22 17:35:43 2014
***************
*** 211,216 ****
--- 211,217 ----
  	lge.4 \
  	${_lindev.4} \
  	${_linux.4} \
+ 	lispintro.4 \
  	lmc.4 \
  	lo.4 \
  	lp.4 \
***************
*** 229,234 ****
--- 230,236 ----
  	mac_stub.4 \
  	mac_test.4 \
  	malo.4 \
+ 	map.4 \
  	mcd.4 \
  	md.4 \
  	mem.4 \
