*** /usr/src/share/man/man4/Makefile.original	Mon Mar 29 17:22:45 2010
--- /usr/src/share/man/man4/Makefile	Wed Jun 30 11:21:43 2010
***************
*** 157,162 ****
--- 157,163 ----
  	led.4 \
  	lge.4 \
  	${_lindev.4} \
+ 	lispintro.4 \
  	lmc.4 \
  	lo.4 \
  	lp.4 \
***************
*** 175,180 ****
--- 176,182 ----
  	mac_stub.4 \
  	mac_test.4 \
  	malo.4 \
+ 	map.4 \
  	md.4 \
  	mem.4 \
  	meteor.4 \
