*** /usr/src/include/Makefile.original	Thu Jun 30 13:19:55 2011
--- /usr/src/include/Makefile	Thu Jun 30 13:22:35 2011
***************
*** 49,54 ****
--- 49,55 ----
  	geom/mirror geom/multipath geom/nop \
  	geom/raid3 geom/shsec geom/stripe geom/virstor \
  	netgraph/atm netgraph/netflow \
+ 	net/lisp \
  	security/audit \
  	security/mac_biba security/mac_bsdextended security/mac_lomac \
  	security/mac_mls security/mac_partition \
