#!/bin/sh
# 
#- /usr/local/etc/rc.d/mapd
#
# Copyright (c) 2010 - 2011 The OpenLISP Project
#
# Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  4. Neither the name of the University nor the names of its contributors
#     may be used to endorse or promote products derived from this software
#     without specific prior written permission.
# 
#  THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  SUCH DAMAGE.
#
#
#  Contributors: 
#               Luigi Iannone <ggx@openlisp.org>
#
# $Id: mapd 183 2011-09-22 16:29:20Z ggx $
#
#
# PROVIDE: mapd
# REQUIRE: DAEMON
#
# Add the following lines to /etc/rc.conf to enable the mapd LISP daemon:
#
# mapd_enable="YES"
# mapd_config="path/to/config/file"
#

. /etc/rc.subr

# Set Some defaults
mapd_enable=${mapd_enable:-"NO"}
mapd_config=${mapd_config:-"/usr/local/etc/mapd/mapd.conf"}

name=mapd
rcvar=`set_rcvar`

load_rc_config ${name}

command="/sbin/mapd"

mapd_flags="$mapd_flags -r $mapd_config"

run_rc_command "$1" 

