*** /usr/src/share/man/man4/Makefile.original	Wed Aug  4 18:29:54 2010
--- /usr/src/share/man/man4/Makefile	Wed Aug  4 18:31:02 2010
***************
*** 182,187 ****
--- 182,188 ----
  	lge.4 \
  	${_lindev.4} \
  	${_linux.4} \
+ 	lispintro.4 \
  	lmc.4 \
  	lo.4 \
  	lp.4 \
***************
*** 200,205 ****
--- 201,207 ----
  	mac_stub.4 \
  	mac_test.4 \
  	malo.4 \
+ 	map.4 \
  	mcd.4 \
  	md.4 \
  	mem.4 \
